### ISSUE TITLE
Release version with support for egui 0.26

### ISSUE THREAD

**Issue by Leinnan** [matthewjberger/enum2egui#4]
1. My PR has one "bug"- it updates README saying that version `0.1.8` supports egui 0.26 which is wrong, the unreleased version `0.2.0` supports it.
2. Is there a chance for a release of `0.2.0` version of the crate on crates.io?

**Comment by matthewjberger** [comment]
No worries, I updated the version in the documentation in the most recent commit and pushed the macro crate and main crate to crates.io

This was made to support some ongoing work related projects of mine and is pretty minimal of a crate, so definitely feel free to fork the crate and turn it into anything you like

**Comment by matthewjberger** [comment]
Fixed in https://github.com/matthewjberger/enum2egui/commit/c9ddfdb1ac8ec638179b6ac37287713e003280cd
