### ISSUE TITLE
Allow changing labels of struct fields/enum variants

### ISSUE THREAD

**Issue by FireFragment** [matthewjberger/enum2egui#5]
Currently, this crate only displays labels of struct fields/enum variants exactly the same as written in code. This results in the interface looking unintuitive and unattractive.

It would be nice, if it was possible to override the text of labels in GUI through some attribute, eg.:
```rust
struct Color {
    #[enum2egui(label="Red")]
    r: u8,
    #[enum2egui(label="Green")]
    g: u8
    #[enum2egui(label="Blue")]
    b: u8
} 
```

Thank you for maintaining this library :)

**Comment by matthewjberger** [comment]
> Thank you for maintaining this library :)

Thank you for the kindness 🙏🏼

I like your idea, and I've updated the crate to version `0.3.7` which supports adding a `label` attribute to struct and enum fields, so now:

```rust
#[derive(Gui)]
pub struct MyColor {
    #[enum2egui(label = "Red")]
    r: u8,

    #[enum2egui(label = "Green")]
    g: u8,

    #[enum2egui(label = "Blue")]
    b: u8,
}
```

Looks like this:

![Screenshot 2024-09-05 at 1 51 41 PM](https://github.com/user-attachments/assets/36ff96fc-6ed0-46f2-8640-8be5b07203d4)
